### ISSUE TITLE
Enable matrix-operation chaining by having matrix-operations panic instead of returning the extra error

### ISSUE THREAD

**Issue by paddie** [skelterjohn/go.matrix#10]
I don't know if there's something clever I'm missing about ignoring errors when trying to chain matrix operations - but having the ability to do this:

``` Go
Y := Z.MinusDense( H.TimesDense(X) )
```

Instead of this:

``` Go
HX, err := H.TimesDense(X)
if err != nil {
    return nil, error
}
Y, err = Z.MinusDense(HX)
if err != nil {
    return nil, error
}
```

Would be terrific. I don't know if maybe having a different import for go.matrix that allowed for the matrix operations to be chained like this would make sense. I was gonna branch this and simply replace all `return *DenseMatrix, error` with `panic(err)` but seeing as this seems to be the most prominent matrix package for Go, I thought I would ask for your thoughts before going in that direction.

**Comment by skelterjohn** [comment]
matrix.Product(matrix.Sum(a, b), c) is exactly as you describe.

**Comment by paddie** [comment]
Ahhh! I had some difficulty navigating the code and thought the times one was what I was looking for. Appreciate it, and thanks for the work on this!

**Comment by skelterjohn** [comment]
My pleasure. Check out github.com/gonum for the next gen of this.
