### ISSUE TITLE
Add float32 functionality.

### ISSUE THREAD

**Issue by Nvveen** [skelterjohn/go.matrix#6]
Using go.matrix for OpenGL calls for example isn't possible without converting each underlying matrix to a float32 slice. It would be nice to see functionality added that allows the user to use this type.

**Comment by skelterjohn** [comment]
I think that, if you're working with opengl, it'd be better to use a matrix lib written specifically with opengl in mind. That is, only 3x3 or 4x4 matrices, backed by float32s. I know that at least one package like this exists, but I'm having a lot of trouble tracking it down.

I'm not going to built float32 support into go.matrix, but it'd be straightforward and fast to write your own function that, for instance, took a DenseMatrix and turned it into a row-major []float32.

**Comment by Nvveen** [comment]
Although I think the overhead for such a conversion is too big for OpenGL requirements, I think I agree go.matrix might be a bit much for the user case scenario's OpenGL development entails.

**Comment by skelterjohn** [comment]
Right. For typical opengl stuff you need only the basic matrix operations -
scale, add, multiply. These things will be super fast if you are only
dealing with 4x4 matrices and you can hard-code everything. For trickier
things that go.matrix can offer, like the various decompositions, the time
spent doing the decomp will overwhelm the time spent converting it between
formats.
